Repository bcit-ci/CodeIgniter, pull requests merged in 2018-06, with the labels that each got.

#5491 Fix sphinx warning message
  user_guide_src/source/installation/upgrade_320.rst
Labels: Documentation

#5516 Use Config::base_url() properly
  system/helpers/html_helper.php
Labels: Bug

#5512 mimes.php: 7z file types changes
  application/config/mimes.php
Labels: Enhancement
