Repository bcit-ci/CodeIgniter, pull requests merged in 2019-09, with the labels that each got.

#5828 Alter php5_validate_id()
  system/libraries/Session/drivers/Session_redis_driver.php
Labels: Bug, Regression

#5831 Fixed HTML type attribute for input field.
  user_guide_src/source/tutorial/create_news_items.rst
Labels: Documentation

#5837 Fix deprecation warning on Travis
  composer.json
Labels: Optimization
