Repository bcit-ci/CodeIgniter, pull requests merged in 2020-01, with the labels that each got.

#5883 image/webp for Image lib
  system/language/english/imglib_lang.php
  system/libraries/Image_lib.php
Labels: Enhancement

#5885 Update documentation for method parse_string
  user_guide_src/source/libraries/parser.rst
Labels: Documentation

#5881 Added FULL OUTER JOIN to QueryBuilder
  system/database/DB_query_builder.php
  user_guide_src/source/database/query_builder.rst
Labels: Enhancement

#5891 Inserted required attribute `lang` in html tags
  application/cache/index.html
  application/config/index.html
  application/controllers/index.html
  application/core/index.html
  application/helpers/index.html
  application/hooks/index.html
  application/index.html
  application/language/english/index.html
  application/language/index.html
  application/libraries/index.html
  application/logs/index.html
  application/models/index.html
  application/third_party/index.html
  application/views/errors/cli/index.html
  application/views/errors/html/index.html
  application/views/errors/index.html
  application/views/index.html
  system/core/compat/index.html
  system/core/index.html
  system/database/drivers/cubrid/index.html
  system/database/drivers/ibase/index.html
  system/database/drivers/index.html
  system/database/drivers/mssql/index.html
  system/database/drivers/mysql/index.html
  system/database/drivers/mysqli/index.html
  system/database/drivers/oci8/index.html
  system/database/drivers/odbc/index.html
  system/database/drivers/pdo/index.html
  system/database/drivers/pdo/subdrivers/index.html
  system/database/drivers/postgre/index.html
  system/database/drivers/sqlite3/index.html
  system/database/drivers/sqlsrv/index.html
  system/database/index.html
  system/fonts/index.html
  system/helpers/index.html
  system/index.html
  system/language/english/index.html
  system/language/index.html
  system/libraries/Cache/drivers/index.html
  system/libraries/Cache/index.html
  system/libraries/Session/drivers/index.html
  system/libraries/Session/index.html
  system/libraries/index.html
  tests/codeigniter/core/Output_test.php
  user_guide_src/source/general/views.rst
  user_guide_src/source/libraries/file_uploading.rst
  user_guide_src/source/libraries/form_validation.rst
  user_guide_src/source/libraries/parser.rst
  user_guide_src/source/tutorial/static_pages.rst
Labels: Enhancement

#5890 Adds a public trans_depth function to determine transaction state
  system/database/DB_driver.php
  user_guide_src/source/database/db_driver_reference.rst
Labels: Enhancement, Feature Request
