Repository bcit-ci/CodeIgniter, pull requests merged in 2022-01, with the labels that each got.

#5690 Corrected grammar
  application/config/config.php
Labels: Documentation

#5684 fixes #5648
  application/config/config.php
  system/core/Log.php
Labels: Enhancement

#5373 prevent _ci_vars from being cached in _ci_cached_vars
  system/core/Loader.php
  tests/codeigniter/core/Loader_test.php
Labels: Enhancement

#5729 NOT BETWEEN syntax error DB where() issue solved
  system/database/DB_driver.php
Labels: Bug
